### ISSUE TITLE
Response is Sent="true" but mail is not sent

### ISSUE THREAD

**Issue by virusmickey** [malithmcr/react-php-contact-form#19]
when i submit the form i get response as sent="true" but when i check my mail there is no mail received in the terminal i have **sh: 1: /usr/sbin/sendmail: not found** this as error message please help im using ubuntu 18.04

**Comment by bretwadleigh** [comment]
You don't seem to have sendmail installed:

https://gist.github.com/adamstac/7462202

**Comment by malithmcr** [comment]
thanks @bretwadleigh

**Comment by malithmcr** [comment]
@all-contributors please add @bretwadleigh  for support

**Comment by malithmcr** [comment]
@all-contributors please add @bretwadleigh for maintenance
