### ISSUE TITLE
axios issues

### ISSUE THREAD

**Issue by harshan89** [malithmcr/react-php-contact-form#7]
In localhost Axios post request is not working on Firefox but works in Chrome.

**Comment by malithmcr** [comment]
Hi @harshan89, 
Could you please open the console and get a screenshot if you see any error message?

Thank you.

**Comment by harshan89** [comment]
Chrome request.

![chrome_request](https://user-images.githubusercontent.com/9652826/58151462-647f3c00-7c87-11e9-9671-a41bdc964281.PNG)

Firefox request.

![firefox_request](https://user-images.githubusercontent.com/9652826/58151467-66e19600-7c87-11e9-9d54-591da4500dd8.PNG)

**Comment by harshan89** [comment]
Anyway will be sorted by adding header('Access-Control-Allow-Headers: Content-Type'); in index.php
Ty

**Comment by malithmcr** [comment]
> Anyway will be sorted by adding header('Access-Control-Allow-Headers: Content-Type'); in index.php
> Ty

Awesome. Thank you
